### PR TITLE
ENH: add requirements for pip-installable package

### LINKED ISSUE #91: Create pip-installable package
[pyCHX](https://github.com/NSLS-II-CHX/pyCHX/blob/d9c71e68030031da102af6731285ff98786c7e91/requirements.txt#L17) depends on this package, which is currently installed directly from GitHub. We need a pip-installable package. It also can be used in other projects (e.g., [summer interns](https://github.com/NSLS-II/summer-interns/pull/5#issuecomment-398731584) work).

### PR DESCRIPTION
**Pull request by mrakitin**
Based on our [lightsource2-tag conda recipe](https://github.com/NSLS-II/lightsource2-recipes/blob/1757decd5025eacfc072b63ac93d1d02ef4ba3f3/recipes-tag/xray-vision/meta.yaml#L21-L26).

Closes #91.

### CODE REVIEW

**Comment by mrakitin** [comment]
Tested locally, it installs fine.
[xray-vision-0.0.7+3.g9227b56.tar.gz](https://github.com/Nikea/xray-vision/files/2119742/xray-vision-0.0.7.3.g9227b56.tar.gz)

**Comment by jrmlhermitte** [comment]
looks good to me
```
pip install xray-vision-0.0.7+3.g9227b56.tar.gz
Successfully built xray-vision
Installing collected packages: kiwisolver, six, cycler, pyparsing, numpy, pytz, python-dateutil, matplotlib, pandas, sip, pyqt5, scipy, xray-vision
Successfully installed cycler-0.10.0 kiwisolver-1.0.1 matplotlib-2.2.2 numpy-1.14.5 pandas-0.23.1 pyparsing-2.2.0 pyqt5-5.10.1 python-dateutil-2.7.3 pytz-2018.4 scipy-1.1.0 sip-4.19.8 six-1.11.0 xray-vision-0.0.7+3.g9227b56
```

imports fine

**Comment by mrakitin** [comment]
Thanks @jrmlhermitte and @danielballan for reviewing and merging!

**Comment by mrakitin** [comment]
It's now uploaded to pypi: https://pypi.org/project/xray-vision/.
@danielballan, how to make a nice description there?

**Pull request merged**
