### PR TITLE
DOC: Remove old argument from docstring

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Is this also a bad line?
https://github.com/ericdill/xray-vision/blob/fix-docstring/xray_vision/backend/mpl/cross_section_2d.py#L166

**Comment by tacaswell** [comment]
good catch @CJ-Wright

**Comment by CJ-Wright** [comment]
Thanks @tacaswell 
Are these functions for general use, I am looking for a way to plot a 2D image stack without too much hassle?  If so can I get an example?

**Comment by tacaswell** [comment]
Yes, they should be.

**Comment by ericdill** [comment]
@CJ-Wright The following should work. (with you having to fill in exactly what data you want to visualize)


```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import sys

from xray_vision import QtGui, QtCore
import numpy as np

from xray_vision.messenger.mpl.cross_section_2d import CrossSection2DMessenger

from xray_vision.qt_widgets import CrossSectionMainWindow

import logging
logger = logging.getLogger(__name__)

def load_cj_data(data_path):
    # use the data path to do some data loading
    # return a list of labels and a list of data
    return return list_of_labels, list_of_data

class StackExplorer(QtGui.QMainWindow):
    def __init__(self, parent=None):
        QtGui.QMainWindow.__init__(self, parent=parent)
        self.setWindowTitle('StackExplorer')
        key_list, data_dict = load_cj_data(data_path)
        self._main_window = CrossSectionMainWindow(data_list=data_dict,
                                                   key_list=key_list)

        self._main_window.setFocus()
        self.setCentralWidget(self._main_window)

app = QtGui.QApplication(sys.argv)
tt = StackExplorer()
tt.show()
sys.exit(app.exec_())
```

This should get you started.  If you can provide a bit more information regarding where the data is coming from (live vs static) then I might be able to better assist you

**Comment by CJ-Wright** [comment]
@ericdill Thank you very much.  My data is being loaded into list of images using TiffStack.  Would it be possible to have the __init__ take on the  data_list and key_list as kwargs?

**Comment by ericdill** [comment]
I mean you have the code snippet there, add those to the init if you so
desire!

**Pull request merged**
