### PR TITLE
WIP: Implementing Enaml version of these widgets so replay can use them easily

### PR DESCRIPTION
**Pull request by ericdill**
This PR is refactoring the bubblegum library so that both the straight PyQt version and the Enaml version use the same matplotlib objects in the backend/ sub-package.  The goal is to write mpl objects that take a live axes object whose parent figure was created external to the matplotlib backend object.

### CODE REVIEW

**Comment by tacaswell** [comment]
@ericdill What is the state of this?

**Comment by ericdill** [comment]
This has not been a priority and it is not under active development

**Comment by ericdill** [comment]
replay is dead

**Comment by ericdill** [comment]
err, enaml implementation of replay is dead

**Pull request closed without merging**
