### PR TITLE
Manual mask

### PR DESCRIPTION
**Pull request by sameera2004**

### CODE REVIEW

**Comment by danielballan** [comment]
@tacaswell We handed this off to you and I think we overshot the MVP. Would you like to take a second more focused look at this, or should I just give it my best effort (positive mask is green, holes are black) and merge?

**Comment by sameera2004** [comment]
@danielballan, @tacaswell , Yes I wanted to remind you about this issue. 
Soon CHX will need to create a manual mask to analysis their new data.

**Comment by sameera2004** [comment]
Thank you very much, @tacaswell and @danielballan.
I think this will be a useful tool for all the beam lines

**Comment by tacaswell** [comment]
More commits are coming.  I will put in a new PR

**Pull request merged**
